* Exercise 0. You should consult the following tutorials for a quick intro and basic help:

"Hands on Programming with R"  by Garret Grolemund 

[[https://learnxinyminutes.com/r/][Learn X in Y Minutes]]

[[https://www.stat.cmu.edu/~larry/all-of-statistics/=R/Rintro.pdf][Larry Waserman R tutorial]]

[[https://github.com/karoliskoncevicius/r_notes/blob/main/README.md][Another optional but handy R tutorial]]

* Exercise 1. The graduated income tax is a concept where people of different incomes are taxed differently.

** Part one
Program a calculator for different income tax rates using R:
Income	Amount Taxed
0-20k	0%
20k-50k	10% of amount over 20,000
50k-70k	15% of amount over 50,000
70k-90k	20% of amount over 70,000
90k-110k	25% of amount over 90,000
110k+	30% of amount over 110,000

For example, if I was to make 80k, I would be taxed at the rate of 10% for the 20-50k amount plus the 15% for the 50-70k amount plus 20% of the amount over 70,000 . 

** Part two
Now building on part 1, turn this into a function.

** Part three 
Now generalize part 2 to do this calculator for a whole list of values… so for example if I had a list of c(100k, 550k, 50k, 10k), write code that could output a corresponding list where the tax calculation was applied to the whole list.

* Exercise 2. 
** Part one
Create a dataframe structure to encapsulate the following data.  
| Name    | Gender | Job          |
|---------|--------|--------------|
| Adam    | M      | Engineer     |
| Bob     | M      | Poet         |
| Cynthia | F      | Scientist    |
| David   | M      | Data Analyst |
| Elisa   | F      | Teacher      |

** Part two

How can I combine this dataframe with the dataframe from part 1? So I can have the numbers corresponding to the job added to the dataframe with people’s names on it? 

| Job           | Salary |
|---------------|--------|
| Data Analyst  |  80000 |
| Poet          |  30000 |
| Teacher       |  50000 |
| Engineer      |  90000 |
| Nurse         |  80000 |
| Auto Mechanic |  74000 |
| Scientist     |  89000 |



** Part three
Apply the function from Exercise 1 onto the table and create a column that calculates “Taxes Paid”.
** Part four
Turn your job table into an excel file using R, or make it a simple database to query. Research the merits of different databases.
